# Generated by Django 3.2.22 on 2023-11-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_zinnia', '0002_fix_djangocms330_incompatible_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestentriesplugin',
            name='featured',
            field=models.BooleanField(blank=True, choices=[(True, 'Show featured entries only'), (False, 'Hide featured entries')], null=True, verbose_name='featured'),
        ),
    ]
